<?php echo $this->partial('#name#/#view#/list.phtml',
                           array(
                                'module'     => $module,
                                'action'     => $action,
                                'areaName'   => $areaName,
                                'table'      => $table,
                                'messages'   => $messages,
                                'module'     => $module
                           )) ?>
