<?php 
echo $this->partial('base/side-menu.phtml',
                          array('module' => $module,
                                'areaName' => $areaName
                        )) ?>

<!-- main-content -->
<div class="main-content">

    <div class="hero-unit">
        <h2><?php echo $this->translate($areaName) ?></h2>
        <p><?php echo $this->translate("description" . ucfirst($areaName)) ?></p>
    </div>


    <?php echo $this->partial('base/message.phtml', array('messages'=>$messages)) ?>

<?php echo $this->partial('base/action-menu.phtml', 
                               array('module'   => $module,
                                     'areaName' => $areaName,
                                     'action'   => $action)) ?>

    <?php echo $this->partial('#name#/#view#/table.phtml',
                              array(
                                'table'   => $table,
                                'module'  => $module,
                               'areaName'=> $areaName,
                                'action'  => $action
                              )) ?>
</div>
<!-- /main-content -->
