<?php 
if ($this->table['content']->getTotalItemCount() <= 0): 

    echo '<h1>' . $this->translate('noResults') . '</h1>';
    
else:
    $maxChar = 100;
    $tableFieldCount = count($this->table['fields']);
    if ($tableFieldCount > 6)
        $maxChar = 80;

    if ($tableFieldCount > 8)
        $maxChar = 60;

    if ($tableFieldCount >= 10)
        $maxChar = 40;
    ?>
    <!-- table -->
        <table class="table table-striped table-bordered">
            <!-- thead -->
            <thead>
                <tr class="well">
                    <?php foreach ($this->table['fields'] as $k => $v): ?>
                    <th><?php echo $this->translate($v) ?></th>
                    <?php endforeach ?>
                    <th class="action-column"><?php echo $this->translate('edit') ?></th>
                    <th class="action-column"><?php echo $this->translate('delete') ?></th>
                </tr>
            </thead>

            <!-- /thead -->
            <tfoot></tfoot>

            <!-- tbody -->
            <tbody>
                <?php foreach ($this->table['content'] as $row): ?>
                <tr>
                    <?php foreach ($this->table['fields'] as $field=>$title): ?>
                        <td>
                        <?php 
                        $r = strip_tags($row->$field);
                        if (strlen($r) > $maxChar) 
                            $r = substr($r,0,$maxChar - 3) . '...';

                        echo ($field === 'status')? $this->translate($r) : $r;
                        ?>
                        </td>
                    <?php endforeach ?>
            
                    <td>
                    <a href="<?php 
                            echo $this->url($areaName,
                                            array('action' => 'edit'),
                                            array('query' => array('id' => $row->id))) ?>" 
                            class="btn">
                            <span class="icon-edit"></span>
                            <?php echo $this->translate('edit') ?>
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-danger btn-delete" href="<?php 
                            echo $this->url($areaName,
                                array('action' => 'delete'),
                                array('query' => array('id' => $row->id))) ?>" >

                            <span class="icon-trash"></span>
                            <?php echo $this->translate('delete') ?>
                        </a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            <!-- /tbody -->
        </table>
        <!-- /table -->
        <?php echo $this->paginationControl(
                        $this->table['content'],
                        'Sliding',
                        '#name#/#view#/pagination',
                        array('route'=>"{$areaName}",
                            'action'=>$this->action)) ?>    

<?php endif ?>
